### ISSUE TITLE
Moving selection on Disk Select Menu (F3) very diffult when using PC joystick

### ISSUE THREAD

**Issue by ghedger** [linappleii/linapple#186]
No explanation for this, will look at it if I have time.

Using a PC joystick (a Sony DualShock 4 in my case) for joystick input works.  However, moving the selection up and down is extremely difficult.  This is no doubt in part due to the grotesque need for a refactor of the Disk Select menu I'm not even sure it's event-driven -- might read SDL keydown directly, don't know, haven't investigated, don't even remember without getting back into the code how SDL 1.2 does this.

At any rate, it makes using the emulator difficult when using a PC Joystick.

**Comment by maxolasersquad** [comment]
My hope with this is to provide a way to map joystick buttons to key presses on the Apple 2 hardware. This will be some time out though.

**Comment by maxolasersquad** [comment]
My proposal is have the following features:
1. **Unified SDL3 Gamepad Pipeline:** Automatic controller detection and layout normalization via `SDL_GameControllerDB`.
2. **Flexible Target Binding:** Gamepad inputs can target Apple II Joystick buttons, analog paddle pots, keyboard keys, sequential text macros, or emulator meta-actions.
3. **Macro & Chord State Machine:** Support for button chords (e.g., `LT + D-Pad Up`), tap vs. hold distinctions, turbo autofire, and automatic command string injection (`CATALOG\r`, `PR#6\r`).
4. **Analog Calibration & Potentiometer Emulation:** Exponential response curves, radial deadzones, and square-to-circle coordinate normalization.
5. **Gyro Controls & Profile Switching:** Gyro/Motion-to-Paddle mapping for tilt-controlled gaming (*Breakout*, *Little Brick Out*), on-screen controller HUD overlays, and per-game auto-profile switching.

## 2. Input Pipeline Architecture

```
┌─────────────────────────────────────────────────────────────────────────────┐
│                           Physical Controller Event                         │
│                    (Xbox / PS5 / Switch Pro / Steam Deck)                   │
└──────────────────────────────────────┬──────────────────────────────────────┘
                                       │
┌──────────────────────────────────────▼──────────────────────────────────────┐
│                           SDL3 Gamepad API Layer                            │
│                 (gamecontrollerdb.txt Normalization & Axes)                 │
└──────────────────────────────────────┬──────────────────────────────────────┘
                                       │
┌──────────────────────────────────────▼──────────────────────────────────────┐
│                    LinApple Macro & Chord State Machine                     │
│                                                                             │
│  ┌─────────────────────────┐  ┌─────────────────────────┐  ┌─────────────┐  │
│  │   Chord Evaluator       │  │    Tap vs Hold Timer    │  │  Autofire   │  │
│  │  (e.g. LT_HELD + Select)│  │ (Short: Key / Long: Menu│  │ (Config Hz) │  │
│  └────────────┬────────────┘  └────────────┬────────────┘  └──────┬──────┘  │
└───────────────┼────────────────────────────┼──────────────────────┼─────────┘
                │                            │                      │
┌───────────────▼────────────────────────────▼──────────────────────▼─────────┐
│                           Action Dispatcher                                 │
│                                                                             │
│  ┌──────────────────┐  ┌──────────────────┐  ┌───────────────────────────┐  │
│  │  Apple II Keys   │  │  Apple II Pots   │  │    Emulator Meta-Action   │  │
│  │ (IJKM / Arrows / │  │  (Paddle 0 / 1   │  │  (Save/Load State, Pause, │  │
│  │   Open Apple)    │  │   $C064 / $C065) │  │   Swap Disk, CRT Shader)  │  │
│  └──────────────────┘  └──────────────────┘  └───────────────────────────┘  │
└─────────────────────────────────────────────────────────────────────────────┘
```

## 3. Macro & Sequential String Injection

In Apple II games and DOS 3.3 / ProDOS sessions, common operations require typing standard commands. LinApple supports **Sequential String Macro Injection**:

```
Gamepad Button Press (e.g. LT + Y)
  │
  ▼
Queue String Macro: "CATALOG\r"
  │
  ▼
Inject Keystroke 1: 'C' ──▶ Wait 2 Frames ──▶ Release 'C'
  │
  ▼
Inject Keystroke 2: 'A' ──▶ Wait 2 Frames ──▶ Release 'A'
  │
  ...
  ▼
Inject Keystroke 8: '\r' (Enter) ──▶ Command Executed!
```

## 4. Analog Potentiometer Calibration & Gyro Controls

Apple II paddles measure resistance (0 to 150 kΩ) translated by a 555 timer into a cycle count (0 to 2820 cycles).

### 4.1 Coordinate Normalization & Response Curves
* **Radial Deadzones:** Prevents stick drift on worn analog sticks.
* **Exponential Curve:** `V_out = sign(V_in) * |V_in|^1.5` providing precision in small movements with rapid reach at full extension.
* **Square-to-Circle Transform:** Normalizes circular analog stick physical bounds to the square corners of vintage Apple II joysticks.

### 4.2 Gyro-to-Paddle Motion Controls
Using SDL3's sensor API (`SDL_GamepadSensorType`), LinApple maps controller tilt (roll and pitch) to Paddle 0 and Paddle 1:
* Tilt left/right -> Steer paddle in *Breakout* or *Arkanoid*.
* Tilt forward/back -> Control elevator in *Flight Simulator II*.

## 5. Configuration Schema (`input.toml`)

```toml
[controller.default]
deadzone_percent = 12
curve_mode = "exponential"
gyro_enabled = true
gyro_sensitivity = 1.25

# Single Button Mappings
[controller.default.buttons]
dpad_up    = { type = "key", key = "UP_ARROW" }
dpad_down  = { type = "key", key = "DOWN_ARROW" }
dpad_left  = { type = "key", key = "LEFT_ARROW" }
dpad_right = { type = "key", key = "RIGHT_ARROW" }
south      = { type = "apple_paddle_button", button = 0 } # Button 0 / Open Apple
east       = { type = "apple_paddle_button", button = 1 } # Button 1 / Solid Apple
north      = { type = "key", key = "SPACE" }
west       = { type = "key", key = "RETURN" }

# Button Chords
[controller.default.chords]
"left_trigger + start"      = { type = "emulator_action", action = "cold_reset" }
"left_trigger + back"       = { type = "emulator_action", action = "toggle_pause" }
"right_trigger + shoulder"  = { type = "emulator_action", action = "save_state_slot_1" }
"left_trigger + shoulder"   = { type = "emulator_action", action = "load_state_slot_1" }
"left_trigger + north"      = { type = "macro_string", text = "CATALOG\r" }
"left_trigger + east"       = { type = "macro_string", text = "RUN\r" }
```
